mod client;
mod config;
mod response;
mod source;

pub use client::WorkloadIdentityAccessToken;
pub use client::WorkloadIdentityClient;
pub use client::WorkloadIdentityError;
pub use config::CredentialSourceConfig;
pub use config::WorkloadIdentityConfig;
pub use config::WorkloadIdentityConfigError;
pub use config::default_token_url;
pub use response::BoundedResponseBodyError;
pub use response::read_bounded_response_body;
pub use source::EnvironmentSubjectTokenSource;
pub use source::FileSubjectTokenSource;
pub use source::MAX_SUBJECT_TOKEN_BYTES;
pub use source::SubjectToken;
pub use source::SubjectTokenError;
pub use source::SubjectTokenProvider;
pub use source::UnavailableSubjectTokenSource;
